#!/usr/bin/env python

#Pingsweep
import ipaddress
import sh
#sh is shell emulator#

#take user input
network = raw_input("Give the subnet you want to sweep using the following format: \n 192.168.10. \n")


#create a file for active hosts
f = open ("hosts.txt", "w+")


#run through the network hosts
for i in range (1,254):
        address = network + str(i)
        try:
                sh.ping(address, "-c 1")
                print address, "is active"
                f.write("{host} \n".format(host=address))
        except sh.ErrorReturnCode_1:
                print "no response from ", i

